import pandas as pd
import matplotlib.pyplot as plt
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
CSV_PATH = os.path.join(OUTPUT_DIR, "gf180_dc.csv")
PNG_PATH = os.path.join(OUTPUT_DIR, "gf180_dc.png")

def main():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    if not os.path.exists(CSV_PATH):
        print(f"Error: {CSV_PATH} not found.")
        return

    print(f"Reading {CSV_PATH}...")
    try:
        # The CSV generated by the TS runner has headers like "v(v-sweep), i(v-sweep)" etc.
        # But wait, run-gf180-dc.ts uses `result.variableNames`.
        # ngspice raw file variables usually are "v(node)", "i(source)".
        # Let's inspect headers dynamically.
        df = pd.read_csv(CSV_PATH)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    print("Columns found:", df.columns.tolist())

    # Identify Vd and Id columns
    # Vd sweep should be the voltage source or the node d.
    # In .dc Vd 0 3.3, the swept variable is often the first column or named 'v-sweep'.
    # In ngspice raw format converted to CSV by our script:
    # First column is usually the sweep variable if it's a DC sweep.
    
    # We expect `v(d_supply)` or `v(d)` and `i(vd)`.
    # `i(vd)` is current through voltage source Vd. Note: spice current convention is into the source, so it might be negative.
    
    x_col = None
    y_col = None

    for col in df.columns:
        c = col.lower()
        if "v(d" in c or "v-sweep" in c: 
             # Prefer v(d) or v(d_supply) if available, but for DC sweep the first var is usually the sweep
             pass
        if "i(vd)" in c or "i(v_d)" in c:
            y_col = col

    # Default to first column as x if not sure
    if x_col is None:
        x_col = df.columns[0]
    
    # If we didn't find specific y_col, try to find something looking like current
    if y_col is None:
        # Try finding 'i(...)'
        for col in df.columns:
            if col.lower().startswith("i("):
                y_col = col
                break

    if y_col is None:
        print("Could not identify current column.")
        return

    print(f"Plotting {y_col} vs {x_col}")

    plt.figure(figsize=(8, 6))
    
    # Convert current to positive if it's source current (negative conventionally)
    # We want Ids flowing D->S. Vd is at drain. Current into Vd + terminal is negative of Ids?
    # Vd is connected to d_supply. Circuit: Vd d_supply 0 0.
    # Current flows from Vd+ -> d_supply -> d -> s -> 0.
    # So current LEAVING Vd+ is Ids.
    # Spice `i(Vd)` is current ENTERING Vd+. So `i(Vd)` should be -Ids.
    # So we expect negative values.
    
    y_data = df[y_col]
    if y_data.mean() < 0:
        y_data = -y_data
        print("Inverted current sign for plotting.")

    plt.plot(df[x_col], y_data, label=f"Vgs=3.3V")
    plt.xlabel(x_col)
    plt.ylabel("Ids [A]")
    plt.title("GF180 NMOS Output Characteristic (W=10u L=10u)")
    plt.grid(True)
    plt.legend()
    
    plt.savefig(PNG_PATH)
    print(f"Saved plot to {PNG_PATH}")

if __name__ == "__main__":
    main()
